"""Tool contracts — canonical interface every connector must implement.

Each tool function returns a ToolResult with:
- ok: bool
- data or error
- trace_id
- redactions applied
"""

from __future__ import annotations

from typing import Any, Protocol

from packages.core.agent_runtime import ToolResult


class NotionConnector(Protocol):
    """Contract for Notion brain operations."""

    async def query_tasks(self, filters: dict[str, Any]) -> ToolResult: ...
    async def create_task(self, payload: dict[str, Any]) -> ToolResult: ...
    async def update_task(self, task_id: str, patch: dict[str, Any]) -> ToolResult: ...
    async def create_run(self, payload: dict[str, Any]) -> ToolResult: ...
    async def append_run_log(self, run_id: str, log_entry: dict[str, Any]) -> ToolResult: ...
    async def create_artifact(self, run_id: str, artifact_meta: dict[str, Any]) -> ToolResult: ...
    async def create_approval_request(self, payload: dict[str, Any]) -> ToolResult: ...
    async def resolve_approval_request(self, approval_id: str, decision: str) -> ToolResult: ...


class OrgoConnector(Protocol):
    """Contract for Orgo computer-use operations."""

    async def create_computer(self, spec: dict[str, Any]) -> ToolResult: ...
    async def destroy_computer(self, computer_id: str) -> ToolResult: ...
    async def get_computer_status(self, computer_id: str) -> ToolResult: ...
    async def screenshot(self, computer_id: str) -> ToolResult: ...
    async def input(self, computer_id: str, actions: list[dict[str, Any]]) -> ToolResult: ...
    async def open_url(self, computer_id: str, url: str) -> ToolResult: ...


class RunnerConnector(Protocol):
    """Contract for Docker sandbox code-runner."""

    async def exec(self, command: str, workdir: str, env_scoped: dict[str, str], network_mode: str) -> ToolResult: ...
    async def put_file(self, path: str, content_base64: str) -> ToolResult: ...
    async def get_file(self, path: str) -> ToolResult: ...


class VoiceConnector(Protocol):
    """Contract for Twilio voice interface."""

    async def say(self, text: str) -> ToolResult: ...
    async def transcribe_callback(self, payload: dict[str, Any]) -> ToolResult: ...


class GLM5Connector(Protocol):
    """Contract for GLM-5 model with function calling."""

    async def chat(self, messages: list[dict], tools: list[dict] | None = None) -> ToolResult: ...
