"""Compare user-provided repo list vs GitHub actual list."""

user_repos = [
    "darya-design-throne", "indigo-azul-catalog", "dashboard-agent-swarm",
    "meishael-mini-meish", "maxx-craft", "thepaulieffect", "voice-web-architect",
    "tanda_cdmx", "amentislibrary", "goat-alliance-scaffold", "botanical-memories",
    "metamorfosis-wellness-journey", "hiring-compass", "goldenhearts",
    "frankenstackbyfranklyai", "nomadasearch", "agent-indigo", "culture-shock-sports",
    "abby-wellness-nexus", "cheggie-lifestyle-finance", "humanatar-genesis-suite",
    "the-pauli-effect", "pv-construction-platform", "emergent-wealth-culture",
    "newworldkids", "chakranaarchonx-os", "macs-agent-portal", "paulis-pope-bot",
    "devika-agent", "synthia", "hustle-claude", "MetaGPT", "voice-agents-fork",
    "pauli-comic-funnel", "VisionClaw", "archonx-skills", "darya-app",
    "lemon-runner", "graphbrain-core", "openclaw-gateway", "king-mode-vr",
    "agent-lightning-fork", "maxx-clipz", "fritco-v2", "macscryptocasino",
    "modernairsolutions", "lapina", "genie-assistant-magic", "smart-plugin-portal",
    "ivettemilo", "nicetohave", "blockerbuiltautosales", "schoolofterabithia",
    "thenetwork", "macstraxx", "terabithiaweb3", "cryptocuties", "hustle",
    "maxxiescraper", "pauli-effect-roi-wizard", "merlina", "memoryblock",
    "sovereign-code-cosmos", "cinematic-smart-funnels-launchpad", "mastertoon",
    "thekey", "youtubetranscripts", "animeta-roblox-craft", "opal-art-preserve",
    "legalai-nexus-core", "reddit-focus-insight", "reddit-focus-finder",
    "rebanada-world-pizza-hub", "crystal-memory-cube", "ivettemushrooms",
    "onboardingglobe", "seoforge-ai-builder", "archon-ui-forge",
    "clandestino-rebellion-launch", "artist-fold-gallery", "cloneflow-ai-sites",
    "sista-rolls-flutter-app", "dispatchhelper2", "codex-craft-forge",
    "aiwear-trend-hub", "que-pedo-cdmx", "morpho-metrics-academy", "black-mirror",
    "lovable-ai-dreamweaver", "archon-ghl-automator", "wherespauli",
    "apify-studiobuilder", "enaswigsandhair", "speak-to-ship-control",
    "kitchen-creations-planner-pro", "veronika-mvp-export", "kauffmans-patterrns",
    "biophillia-blog", "thepuppetmaster", "yappyverse-genesis-project", "la-silueta",
    "balldontlie", "lamonarchaintl", "FRITHCO", "BOILER-BOYZ", "BOILERBOYZ",
    "next-video-starter", "youtube-monster-tran", "pickaxe-nanobanana-g",
    "yappyverse-newsletter", "miranda-portfolio-spark", "promptation",
    "kinetic-code-canvas-dream", "p-72343185", "chatgami-supabuddy",
    "r-108043-e63b540f", "r-108043", "nodev", "notion-blog", "akash-orbit-platform",
    "portal-mini-store-template-main", "dash-vega-luxe", "yappyverse-merch-forge",
    "glassy-focus-flow", "arkan-os-branding", "golden-heart-compass-ai",
    "yappyverse-drop-control", "digital-odyssey-scroll", "ani-maze",
    "nextjs-enterprise-boilerplate", "WEB3SAAS-APP", "Open-clipz", "chat-bot-template",
    "Rube-remix", "yappyverse", "AVATAR", "seattle-reuse-exchange-v2", "frithco-remix",
    "frithco-2.0", "Business-Website-Template-kimi-K2", "remixyoursite.com",
    "ARCHON-X2.0", "infinite-agentic-loop", "GSAP-Awwwards-Website-",
    "pauli-brand-guidelines", "-e-commerce-remix", "sweetmushrooms", "web3sass",
    "tila-airplant-ecommerce", "pauli-story-tool-kit",
    "Social-Media-Post-Generator---Encore.dev", "jzuart-dj-saas",
    "claude-kosmos-2_5-containerized", "react-agent-darya-3.0", "Raft-Landing-Page",
    "portfolio-starter", "darya-design-agent", "MAXX-Research", "maxx-coze-studio",
    "Lumina-DiMOO-image-generator", "Paper2Video-science-avatar", "geist-font-design",
    "outlines-second-brain", "AutoAgent", "evershop-e-commerece", "base-stack-vite",
    "reel-flux-2", "open-lovable", "OPENTHC", "hustle-claude-code",
]

github_repos = [
    "-e-commerce-remix", "-la-pina-cdmx", "-lightning-claude-memory-agent",
    "-yt-knowledge-extractor", "AFRO-CLIPZ", "AI-Youtube-Shorts-Generator",
    "AKASHPORTFOLIO", "ARCHON-X2.0", "AVATAR", "AdventureLog-kupri",
    "Agentic-AIGC-MAXX-EDITS", "AionUi-cowork", "AutoAgent", "BMAD-METHOD",
    "BOILER-BOYZ", "BOILERBOYZ", "Business-Website-Template-kimi-K2",
    "CHEGGIE-AI-Trader", "CLONELY-FANZ", "Darya-designs", "ECO-TOUR-DIRECTORY",
    "FRITHCO", "GPT-Agent-im-ready", "GSAP-Awwwards-Website-", "Kupuri-studios",
    "Lumina-DiMOO-image-generator", "MAXX-Research", "MAXX-Video-Agent", "MetaGPT",
    "Nextjs-Ecommerce", "OPENTHC", "Open-clipz", "POSTA-STUDIO.V2",
    "Paper2Video-science-avatar", "Pauli-claw-work", "Pauli-spec-kit",
    "Raft-Landing-Page", "Rube-remix", "Social-Media-Post-Generator---Encore.dev",
    "Suenos--very_good_templates", "Synthia-3.0", "Synthia-4.2", "Telegram-bot",
    "VIPposta", "VisionClaw", "WEB3SAAS-APP", "abby-wellness-nexus", "acip",
    "actual-stash", "afroscribble", "agent-indigo", "agent-kupuri-template",
    "agent-zero-Fork", "agent_flywheel_clawdbot_skills_and_integrations",
    "ai-sdk-computer-use", "ai-tool-kit", "airbnbauto", "aiwear-trend-hub",
    "aiwear-trend-hub-c0e24ba8", "akash-engine-2.0", "akash-last-edit",
    "akash-master-files", "akash-master-files-2", "akash-master-files-3",
    "akash-master-files.2.0", "akash-master.1.0", "akash-orbit-platform",
    "allweatherroofs", "alphadeltarecycling", "amentislibrary", "ani-maze",
    "animeta-roblox-craft", "apify-studiobuilder", "archon-ghl-automator",
    "archon-lovable-nexus", "archon-ui-forge", "archonx-os", "arkan-os-branding",
    "artist-fold-gallery", "auto-shop-turkey", "balldontlie", "base-stack-vite",
    "biophillia-blog", "black-mirror", "blockerbuiltautosales", "botanical-memories",
    "breatheinternational", "butterflytracker", "cafe-cultura-", "chakrana",
    "chat-bot-template", "chatgami-supabuddy", "chef-code-ide",
    "cheggie-lifestyle-finance", "chromium-fork-browser",
    "cinematic-smart-funnels-launchpad", "clandestino-rebellion-launch",
    "claude-kosmos-2_5-containerized", "claude-suna-kortix", "claude-task-master",
    "clawdbot-Whatsapp-agent", "cloneflow-ai-sites", "coachdavis",
    "codex-craft-forge", "coding_agent_session_search", "coding_agent_usage_tracker",
    "continue-claude-agent", "cruise-reposition-oasis", "crush", "cryptocuties",
    "crystal-memory-cube", "cult-directory-template", "culture-shock-sports",
    "cultureshocksports", "darya-design-agent", "darya-design-throne",
    "darya-next-js-landing-page", "dash-vega-luxe", "dashboard-agent-swarm",
    "ddev-diffy-agent-zero-", "devika-agent", "digital-odyssey-scroll",
    "dispatchhelper", "dispatchhelper2", "emergent-wealth-culture",
    "enaswigsandhair", "evershop-e-commerece", "factory-droid-wrap-",
    "fancynancyai", "fish-on-texas", "flow-profit", "frankenstackbyfranklyai",
    "fritco-locale-scaffold", "fritco-v2", "frithco-2.0", "frithco-3.0",
    "frithco-final-version", "frithco-remix", "geist-font-design",
    "genie-assistant-magic", "glassy-focus-flow", "goat-alliance-scaffold",
    "goatalliance", "golden-heart-compass-ai", "goldenhearts", "hiring-compass",
    "humanatar-genesis-suite", "hustle", "hustle-claude", "hustle-claude-code",
    "image-template", "impact-city-builder-verse", "indigo-azul-catalog",
    "infinite-agentic-loop", "interactive-artifact", "ivettemilo", "ivettemushrooms",
    "jeannieflow-", "jzuart-dj-saas", "kauffmans-patterrns",
    "kinetic-code-canvas-dream", "kitchen-creations-planner-pro",
    "kupuri-media-website", "kupuri-studios-landing", "la-silueta", "lamonarchaintl",
    "landscaping1", "lapina", "legalai-nexus-core", "leon-avatar-fork-",
    "lovable-ai-dreamweaver", "lux-desktop-claude", "macs-agent-portal",
    "macscryptocasino", "macstraxx", "mastertoon", "maxx-casino-portal", "maxx-clipz",
    "maxx-coze-studio", "maxx-craft", "maxxclipz", "maxxiescraper",
    "meishael-mini-meish", "memoryblock", "merlina", "metamorfosis-wellness-journey",
    "metamorphsis-cdmx", "midday-suelta-app", "mini-meish", "miranda-portfolio-spark",
    "modernairsolutions", "monorepo-turborepo", "morpho-metrics-academy",
    "nano-banana-generator-pauli-fork", "newworldkids", "next-forge",
    "next-video-starter", "nextjs-ai-chatbot", "nextjs-commerce",
    "nextjs-enterprise-boilerplate", "nexusgymcdmx", "nicetohave", "nodev",
    "nomadasearch", "nomaticthecost", "notion-blog", "onboardingglobe",
    "onlook-synthi", "opal-art-preserve", "open-agent-platform-pauli",
    "open-interpreter-fork", "open-lovable", "opencode", "outlines-second-brain",
    "p-72343185", "pauli-agent-S-computer-use-", "pauli-beads", "pauli-brand-guidelines",
    "pauli-comic-funnel", "pauli-deep-research", "pauli-design-resources-for-developers",
    "pauli-effect-roi-wizard", "pauli-hyperedit", "pauli-iron-claw",
    "pauli-remote-screen-", "pauli-security-red-hat-", "pauli-story-tool-kit",
    "pauli__mail", "paulis-deep-agent", "paulis-pope-bot",
    "paulisworld-openclaw-3d", "payload-rancho-santiago", "peter-sung",
    "peter-sung-website", "phone-call-assistant", "pickaxe-nanobanana-g",
    "portal-mini-store-template-main", "portfolio-starter", "postatees-studio",
    "postateesstudio-", "postateesstudioV.1", "postiz-maxx-clipz", "promptation",
    "prompts", "pv-construction-platform", "qr-code-maker", "que-pedo-cdmx",
    "r-108043", "r-108043-e63b540f", "react-agent-darya-3.0",
    "rebanada-world-pizza-hub", "reddit-focus-finder", "reddit-focus-insight",
    "reel-flux", "reel-flux-2", "remixyoursite.com", "sassyscraper",
    "schoolofterabithia", "seattle-reuse-exchange", "seattle-reuse-exchange-v2",
    "second-brain-agent", "seoforge-ai-builder", "serene-studio-flow-hub",
    "shirt-shop-example", "sista-rolls-flutter-app", "skills-introduction-to-github",
    "smart-plugin-portal", "sovereign-code-cosmos", "speak-to-ship-control",
    "speedtolead", "spy-scape-mustang-maXx", "strapi-cloud-template-blog-e8d531af4f",
    "strapi-template", "strapi-template-new-world-kids", "strix-ai-que-pedo--",
    "sweet-psilocybe-app", "sweet-psilocybe-landing", "sweetmushrooms", "synthia",
    "synthia-4.1", "synthia-demo", "tanda_cdmx", "terabithia", "terabithiaweb3",
    "the-minority-report", "the-pauli-effect", "the-smoke", "thekey", "thenetwork",
    "thepaulieffect", "thepuppetmaster", "tila-airplant-ecommerce", "trail-mixx",
    "trail-mixx-source-code",
    "ui-ux-pro-max-skill-ht27tps-github.com-nextlevelbuilder-ui-ux-pro-max-skill",
    "v0-leonradio-website", "vallarta-voyage-explorer", "veronika-mvp-export",
    "veronika-mvp-final", "voice-agents-fork", "voice-web-architect", "web3sass",
    "wherespauli", "world-matrix", "yappyverse", "yappyverse-drop-control",
    "yappyverse-genesis-project", "yappyverse-merch-forge", "yappyverse-newsletter",
    "youtube-monster-tran", "youtubemonster", "youtubemonster2.1",
    "youtubetranscripts",
]

user_set = set(user_repos)
github_set = set(github_repos)

user_lower = {r.lower(): r for r in user_repos}
github_lower = {r.lower(): r for r in github_repos}

print(f"User list count:  {len(user_set)}")
print(f"GitHub count:     {len(github_set)}")

user_not_github = sorted([u for low, u in user_lower.items() if low not in github_lower])
github_not_user = sorted([g for low, g in github_lower.items() if low not in user_lower])

print(f"\nIn user list but NOT on GitHub ({len(user_not_github)}) — likely name mismatches or private repos:")
for r in user_not_github:
    print(f"  {r}")

print(f"\nOn GitHub but NOT yet assigned ({len(github_not_user)}):")
for r in github_not_user:
    print(f"  {r}")
